// <auto-generated />
namespace MediaCatalog.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class productauthorlocid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(productauthorlocid));
        
        string IMigrationMetadata.Id
        {
            get { return "201704192137474_product-author-locid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
